checks:
    javascript: true
build:
    environment:
        node: v12
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
        tests: true